# Generated by Django 5.0.3 on 2024-03-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_dob_alter_student_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos/', verbose_name='Profile Photo'),
        ),
    ]
