# Generated by Django 5.0.3 on 2024-03-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Teacher_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('assignment_json', models.JSONField()),
                ('total_marks', models.IntegerField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_id', models.IntegerField(null=True)),
            ],
        ),
    ]
