# Generated by Django 5.0.3 on 2024-03-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsClass',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255)),
                ('smobile', models.CharField(max_length=20)),
                ('semail', models.EmailField(max_length=254, unique=True)),
                ('Teacher_id', models.IntegerField()),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
