# Generated by Django 5.0.3 on 2024-03-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsclass',
            name='semail',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
