# Generated by Django 5.0.3 on 2024-03-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_studentsclass_semail_delete_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('answersheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_id', models.IntegerField()),
                ('test_id', models.IntegerField(max_length=255)),
                ('answersheet_json', models.JSONField()),
                ('achieved_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('result_generated', models.TextField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_id', models.IntegerField(null=True)),
            ],
        ),
    ]
