# Generated by Django 5.0.3 on 2024-03-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_remove_student_user_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='teacher_photos/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
